name: Pull request
on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Setup yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Install node-modules
        run: yarn install
      - name: Build app
        run: yarn build
